version: '3.8'

services:
  jobmanager:
    image: registry.cn-shanghai.aliyuncs.com/frwan-public/flink:1.20.0-scala_2.12-java11
    container_name: flink-jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        jobmanager.memory.process.size: 2048m
        taskmanager.memory.process.size: 6144m
        taskmanager.numberOfTaskSlots: 4
        parallelism.default: 8
    volumes:
      - flink-checkpoints:/opt/flink/checkpoints
      - flink-savepoints:/opt/flink/savepoints
      - ./jobs:/opt/flink/jobs
    networks:
      - flink-network

  taskmanager1:
    image: registry.cn-shanghai.aliyuncs.com/frwan-public/flink:1.20.0-scala_2.12-java11
    container_name: flink-taskmanager1
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.memory.process.size: 6144m
        taskmanager.numberOfTaskSlots: 4
        parallelism.default: 8
    volumes:
      - flink-checkpoints:/opt/flink/checkpoints
      - flink-savepoints:/opt/flink/savepoints
      - ./jobs:/opt/flink/jobs
    networks:
      - flink-network

  taskmanager2:
    image: registry.cn-shanghai.aliyuncs.com/frwan-public/flink:1.20.0-scala_2.12-java11
    container_name: flink-taskmanager2
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.memory.process.size: 6144m
        taskmanager.numberOfTaskSlots: 4
        parallelism.default: 8
    volumes:
      - flink-checkpoints:/opt/flink/checkpoints
      - flink-savepoints:/opt/flink/savepoints
      - ./jobs:/opt/flink/jobs
    networks:
      - flink-network

volumes:
  flink-checkpoints:
  flink-savepoints:

networks:
  flink-network:
    driver: bridge
